In [15]:
import numpy as np
import pandas as pd

## **1. Description of the problem** ##

## **2. Pseudocode of implemented algorithms** ##

## **3. Results of computational experiments** ##

## **4. 2D Visualization** ##

### **Reading TSP A and TSP B instances** ##

In [8]:
tsp_a = pd.read_csv('../data/TSPA.csv', sep=';', header=None)
tsp_a.columns = ['x', 'y', 'cost']

tsp_b = pd.read_csv('../data/TSPB.csv', sep=';', header=None)
tsp_b.columns = ['x', 'y', 'cost']

### **Reading files with best solutions** ##

In [21]:
tsp_a_random = np.array(pd.read_csv('results/TSPA_random.csv', sep=';', header=None).values).flatten()
tsp_a_nn_end = np.array(pd.read_csv('results/TSPA_nn_end.csv', sep=';', header=None).values).flatten()
tsp_a_flexible = np.array(pd.read_csv('results/TSPA_nn_flexible.csv', sep=';', header=None).values).flatten()

In [ ]:
tsp_b_random = pd.read_csv('results/TSPB_random.csv', sep=';', header=None)
tsp_b_nn_end = pd.read_csv('results/TSPB_nn_end.csv', sep    =';', header=None)
tsp_b_flexible = pd.read_csv('results/TSPB_nn_flexible.csv', sep=';', header=None)

## **5. Display of the results** ##

### **5.1. TSP A instance** ###

#### **5.1.1. Random solution** ####

In [19]:
tsp_a_random

array([ 64,  61, 118,  84, 127,  53,   8, 112,  62, 151,  20, 117, 183,
       105, 128, 178,  55, 100, 109,  19,  47, 120,  50,   0, 140, 198,
        96, 103, 133, 148,  27, 165,  68, 199,  74, 162, 123, 175, 135,
       132, 185,  91, 143, 176,  65, 186,  72, 164, 156,  15,  77,  59,
       102,  99, 116,  11, 159,  46, 124,  97,   9, 110, 126,  63,  48,
       149, 160,   3, 144,  40, 182, 114, 137, 155,  70, 158, 189,  42,
        14,  34,  37, 167,  12,  78,  66, 170,  13, 187, 179,  89,  10,
       121,  41,  25, 191,   1,  26, 190,  87, 106,  64])

#### **5.1.2. Nearest neighbour adding new node at the end** ####

In [22]:
tsp_a_nn_end

array([124,  94,  63,  53, 180, 154, 135, 123,  65, 116,  59, 115, 139,
       193,  41,  42, 160,  34,  22,  18, 108,  69, 159, 181, 184, 177,
        54,  30,  48,  43, 151, 176,  80,  79, 133, 162,  51, 137, 183,
       143,   0, 117,  46,  68,  93, 140,  36, 163, 199, 146, 195, 103,
         5,  96, 118, 149, 131, 112,   4,  84,  35,  10, 190, 127,  70,
       101,  97,   1, 152, 120,  78, 145, 185,  40, 165,  90,  81, 113,
       175, 171,  16,  31,  44,  92,  57, 106,  49, 144,  62,  14, 178,
        52,  55, 129,   2,  75,  86,  26, 100, 121, 124])

#### **5.1.3. Nearest neighbour adding new node anywhere** ####

In [23]:
tsp_a_flexible

array([143, 183,  89, 186,  23, 137, 176,  80,  79,  63,  94, 124, 152,
        97,   1, 101,   2, 120, 129,  55,  49, 102, 148,   9,  62, 144,
        14, 178, 106, 165,  90,  81, 196,  40, 119, 185,  52,  57,  92,
       179, 145,  78,  31,  56, 113, 175, 171,  16,  25,  44,  75,  86,
        26, 100,  53, 154, 180, 135,  70, 127, 123, 162, 133, 151,  51,
       118,  59,  65, 116,  43, 184,  35,  84, 112,   4, 190,  10, 177,
        30,  54,  48, 160,  34, 146,  22,  18, 108,  69, 159, 181,  42,
         5, 115,  41, 193, 139,  68,  46,   0, 117, 143])

### **5.2. TSP B instance** ###

#### **5.2.1. Random solution** ####

In [ ]:
tsp_b_random

#### **5.2.2. Nearest neighbour adding new node at the end** ####

In [ ]:
tsp_b_nn_end

#### **5.2.3. Nearest neighbour adding new node anywhere** ####

In [ ]:
tsp_b_flexible

## **6. Usage of solution checker**

## **7. Conclusions**